LANG = {
  PROCESSING: 'processing..',
  SAVE: 'Save',
  CONFIRM: 'Confirm',
  CANCEL: 'Cancel',
  EDIT: 'Edit',
  PER_USER: 'per user',
  PAY: 'Pay',
  JOIN: 'Join in',
  NAME: 'Name',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  LOGIN: 'Login',
  LOGOUT: 'Logout',
  CLOSE: 'Close',
  UPDATE: 'Update',

  EVENT: 'Event',
  EVENT_LIST: 'Event List',
  EVENT_NEW: 'New event',
  EVENT_EDIT: 'Edit event',
  EVENT_NAME: 'Event name',
  EVENT_DESCRIPTION: 'Event description',
  EVENT_PAYMENT_MODE: 'Payment Mode',
  EVENT_SELECTED: 'Selected Event',
  EVENT_FIXED: 'Fixed value',
  EVENT_VARIED: 'Varied value',
  EVENT_DIVIDED: 'Divided value',
  EVENT_INFORM_PRICE_FIXED: 'Inform event price fixed',
  EVENT_INFORM_PRICE_TOTAL: 'Inform event price total',
  EVENT_CONFIRM_EDIT: 'Do confirm event edit',
  EVENT_CONFIRM_NEW: 'Do confirm event new',
  EVENT_CONFIRM_USER_PAY: 'Does confirm "_NAME_" has pay $ "_VALUE_"?',
  EVENT_CONFIRM_USER_JOIN: 'Does confirm "_NAME_" join in?',
  EVENT_INFORM_PAYMENT_AMOUNT: 'Inform payment amount',
  
  USER: 'User',
  USER_LIST: 'User List',
  USER_CONFIRM_NEW: 'Do confirm new user "_NAME_"?',
  USER_CONFIRM_EDIT: 'Do confirm edit user "_NAME_"?',
  USER_NEW: 'New user',
  USER_EDIT: 'Edit user',
  USER_NAME: 'User name',
  USER_EMAIL: 'User Email',
};
