// idioma em português-brasil
LANG = {
  PROCESSING: 'processando..',
  SAVE: 'Gravar',
  CONFIRM: 'Confirmar',
  CANCEL: 'Cancelar',
  EDIT: 'Editar',
  PER_USER: 'por usuário',
  PAY: 'Pagar',
  JOIN: 'Junte-se',
  NAME: 'Nome',
  EMAIL: 'Email',
  PASSWORD: 'Senha',
  LOGIN: 'Conectar',
  LOGOUT: 'Sair',
  CLOSE: 'Fechar',
  UPDATE: 'Atualizar',

  EVENT: 'Evento',
  EVENT_LIST: 'Lista de Eventos',
  EVENT_NEW: 'Novo evento',
  EVENT_EDIT: 'Editar evento',
  EVENT_NAME: 'Nome do evento',
  EVENT_DESCRIPTION: 'Descrição do evento',
  EVENT_PAYMENT_MODE: 'Forma de pagamento',
  EVENT_SELECTED: 'Evento selecionado',
  EVENT_FIXED: 'Valor fixo',
  EVENT_VARIED: 'Valor variado',
  EVENT_DIVIDED: 'Valor dividido',
  EVENT_INFORM_PRICE_FIXED: 'Informe o valor fixo do evento',
  EVENT_INFORM_PRICE_TOTAL: 'Informe o valor total do evento',
  EVENT_CONFIRM_EDIT: 'Confirmar a edição do evento',
  EVENT_CONFIRM_NEW: 'Confirmar o novo evento',
  EVENT_CONFIRM_USER_PAY: 'Confirma que "_NAME_" pagou R$ "_VALUE_"?',
  EVENT_CONFIRM_USER_JOIN: 'Confirmar que "_NAME_" participa?',
  EVENT_INFORM_PAYMENT_AMOUNT: 'Informar valor do pagamento',

  USER: 'Usuário',
  USER_LIST: 'Lista de Usuários',
  USER_CONFIRM_NEW: 'Confirme o novo usuário "_NAME_"?',
  USER_CONFIRM_EDIT: 'Confirmar a edição do usuário "_NAME_"?',
  USER_NEW: 'Novo usuário',
  USER_EDIT: 'Editar usuário',
  USER_NAME: 'Nome do usuário',
  USER_EMAIL: 'Email do usuário',
};
